### ISSUE TITLE
Feature request for the module

### ISSUE THREAD

**Issue by remiverdel** [cdverrett94/overhead-tile-fade-for-all-tokens#1]
Hi!

Love your module, it was exactly what me and my co-dm were looking for but we were missing a feature to use it properly in game. When an enemy token was hidden, it still revealed the tree tile as transparent, making players doubt that something was lurking under a tree somewhere. 
Could there be an option to not show the tile as transparent if the token underneath is hidden ?
Also could it be possible to have an option to only show party members under tiles but not any enemies?

Thanks again for your work !

**Comment by cdverrett94** [comment]
I'll take a look and see what I can do.

**Comment by cdverrett94** [comment]
@remiverdel Can you check out the attached image for the settings? Here's a summary of the additions:

Fade Overhead Tiles For All - should this tile specifically fade for all tokens that meet the below criteria. Allows some tiles to only fade for the token underneath it.

Fade For Players when Who is Under Tile? - 
     Players - fade the tile when any token with a friendly disposition goes underneath. defaults to on
     Neutral - same as above except with the neutral disposition. defaults to on
     Enemies - same as prior two options except with the hostile disposition. defaults to on
     Hidden - fade the tile when a hidden token goes underneath. defaults to off



Let me know your thoughts here. I need to clean up the wording for the settings, but I'll knock that out once I've got it all verified working 100%. I've got it mostly working, but want to bug test some more. 


![New Options](https://user-images.githubusercontent.com/11931255/124331005-305bf200-db54-11eb-9527-c58927f033fe.png)

**Comment by remiverdel** [comment]
Hi man,

It seems awesome! I though at first an option in the module settings but putting it per tile is a much better idea, it can be so much more precise and cover a very wide variety of uses for everyone!

Thanks for listening to the feedback and acting on it! I really appreciate it and will implement it in my home game as soon as it releases, be sure of it!

Cheers,

Remi

**Comment by cdverrett94** [comment]
Yeah, it being per tile made more sense to me since I was already implementing the "fade for everyone" setting per tile. Like you said, it gives greater flexibility for different uses and currently all of the setting per tile will default to how it is now. So if you wanted everything to be how it is now, you don't have to do anything. The only exception is that fading the tile for everyone for a hidden token does default to off. That kind of made more sense to me. So in your use case if the only change you wanted was for the hidden tokens to not trigger the fade for all, then no changes should be required on a per tile basis.

**Comment by remiverdel** [comment]
Sure, the defaults values make sense to me also. Showing everyone players, neutrals and ennemies should encompass the needs of the majority of DMs using this module. And if you want to fine tune a few things, it’s only a few click away.
I may have an idea but really I don’t know any coding at all and it might maybe need coding outside of the initial scope of the module, but maybe a function for copying and pasting tile settings to other tiles or a selection of multiple tiles? What do you think? Of course it’s really just a bonus and I’m sure it’s not as easy as it sounds, but it could save some time for DMs while prepping a session. (Maybe with a tool on the left side of the interface? If I remember correctly Token Attacher has in it’s UI a similar thing with a copy and paste button)

**Comment by cdverrett94** [comment]
So I was actually planning on making macros that I would ship with the module to change the settings of a tile or tiles pretty easily for the module specific settings. So a macro for each of the settings to toggle it. I could also add a Macro that would pull up a config window with all of the modules available settings and you could apply those settings to all selected overhead tiles.

**Comment by remiverdel** [comment]
That’s a great idea. I assume it would be way easier than adding buttons or anything to Foundry’s UI and in the macro bar it could be executed pretty quickly during the prep time. I’m all for it!

**Comment by cdverrett94** [comment]
Awesome. I haven't written those yet, but shouldn't be too hard. I'll try and get this release pushed this weekend.

**Comment by remiverdel** [comment]
Awesome man. Good luck on all the work. Can’t wait to have it in my hands!

Cheers,

Remi

**Comment by cdverrett94** [comment]
New version released. Check it out and let me know if you run into any issues or have improvements to how things are laid out.

**Comment by remiverdel** [comment]
Sorry for the time delay, I was out of town.

I tried it and it’s working pretty fine on my end. Thanks for the amazing work.

Cheers,

Remi

**Comment by cdverrett94** [comment]
No worries! Thanks for the feedback and request!
