### ISSUE TITLE
Native compatibility with levels module

### ISSUE THREAD

**Issue by uniwars** [cdverrett94/overhead-tile-fade-for-all-tokens#2]
Hi, I tried to use the overhead tile fead option to deactive it for a levels made building but that seems to not work 
![image](https://user-images.githubusercontent.com/65986545/124381319-2526d480-dcc2-11eb-9448-6cda4eded52d.png)
I unchecked all boxes for all the different tile but still see tokens of different levels between floors, and even if for example my token is at second floor he will see the floor behind his feet and so doesn't see the token at first floor but it is still possible to point the mouse"s cursor on that token and see his name/health/etc
![image](https://user-images.githubusercontent.com/65986545/124381455-fc530f00-dcc2-11eb-81c9-ca08f343c977.png)

I used the levels module sample map

**Comment by cdverrett94** [comment]
SSo I did some testing with the sample map in the Levels module. If I disable the Overhead Tile Fade for All Tokens module, the issue still persists for me. Can you try disabling this module and see if it still happens for you? If it's still happening when this module isn't active, then that points to it being an issue with Levels and not this one. If it goes away, then I'll have to dig deeper.

**Comment by uniwars** [comment]
Yeah it was from the sample map side, sorry for the issue, thanks
